- hosts: localhost
  tasks:
    - name: Pull Docker image
      docker_image:
        name: jaymeenk/scientific-calculator:latest
        source: pull

    - name: Run calculator container
      docker_container:
        name: scientific-calculator
        image: jaymeenk/scientific-calculator:latest
        state: started
        ports:
          - "8085:8080"